### ISSUE TITLE
Fehlerhafte Spider - Log Files nur 5kb

### ISSUE THREAD

**Issue by VolkerSchroeder13** [PIMS-ORG/PIMS#122]
Aniforte
Valetumed
Talesandtails
Speed
Smoothiedog
Pavo
Hunter
Bense-Eicke

**Comment by finnbechinka** [comment]
Hab ich mir angeguckt. Die haben alle ihre Webseiten verändert.

**Comment by finnbechinka** [comment]
Der Code von SmoothieDog ist nicht komplett. Das hatte Maurice wohl nie fertig gemacht.

**Comment by finnbechinka** [comment]
Pavo scheint bei mir zu Funktionieren

**Comment by VolkerSchroeder13** [comment]
> Pavo scheint bei mir zu Funktionieren

jo, bei mir auch. Scheint temporär gewesen zu sein

**Comment by VolkerSchroeder13** [comment]
Hey Finn, wie weit bist du hier? 
Aniforte bräuchte ich dringend ;-)

**Comment by finnbechinka** [comment]
Ja ich Aniforte habe ich fertig. Mit Valetumed muss ich mich nochmal ausgiebiger beschäftigen, da werde ich mit der spider (aber nicht im Browser) weitergeleitet und deshalb funktioniert nichts, muss ich gucken, ob ich das umgehen kann. Talesandtails ist so 90-95 % fertig.

Ich push das aber dann gleich mit dem aktuellen stand auf master, dann sollte zumindest Aniforte wieder funktionieren.

**Comment by VolkerSchroeder13** [comment]
Aniforte läuft auf nen Fehler

V:\Scrape\PIMS\PIMS\PIMS>scrapy crawl Aniforte
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\scrapy\cmdline.py", line 153, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\scrapy\crawler.py", line 290, in __init__
    configure_logging(self.settings, install_root_handler)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\scrapy\utils\log.py", line 102, in configure_logging
    install_scrapy_root_handler(settings)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\scrapy\utils\log.py", line 112, in install_scrapy_root_handler
    _scrapy_root_handler = _get_handler(settings)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\scrapy\utils\log.py", line 129, in _get_handler
    handler = logging.FileHandler(filename, mode=mode, encoding=encoding)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
OSError: [Errno 22] Invalid argument: 'V:\\Scrape\\PIMS\\PIMS\\PIMS\\logs\\log_2023-11-17_08:11:42.308341_Aniforte.log'

V:\Scrape\PIMS\PIMS\PIMS>

**Comment by VolkerSchroeder13** [comment]
Die Doppelpunkte gehen wahrscheinlich nicht

**Comment by finnbechinka** [comment]
Ist gefixt.

**Comment by VolkerSchroeder13** [comment]
läuft, aber spontan gesehen, dass die Preise nicht passen

'ean': '4260606713575',
 'id': 'A10000360',
 'image_urls': ['https://www.aniforte.de/cdn/shop/products/nassfutter-pferd-pur-646973.jpg?v=1641905738&width=1200',
                'https://www.aniforte.de/cdn/shop/products/nassfutter-pferd-pur-833723.jpg?v=1641905738&width=1200',
                'https://www.aniforte.de/cdn/shop/products/nassfutter-pferd-pur-253225.jpg?v=1641905738&width=1200',
                'https://www.aniforte.de/cdn/shop/products/nassfutter-pferd-pur-474935.jpg?v=1641905738&width=1200',
                'https://www.aniforte.de/cdn/shop/products/nassfutter-pferd-pur-979271.jpg?v=1676054317&width=1200',
                'https://www.aniforte.de/cdn/shop/products/nassfutter-pferd-pur-290096.jpg?v=1676054317&width=1200',
                'https://www.aniforte.de/cdn/shop/products/nassfutter-pferd-pur-144126.jpg?v=1676054317&width=1200'],
 'images': None,
 'parent': 'A10000359',
 'price': '3799',

**Comment by VolkerSchroeder13** [comment]
jo, Preis passt
Bilder und Kategorien klemmen noch ;-)

**Comment by finnbechinka** [comment]
Ich sehe bei mir kein Problem mit Bildern oder Kategorien. Was ist da denn Falsch?

**Comment by VolkerSchroeder13** [comment]
Bei einigen (anscheinend neu angelegten) Produkt fehlen die.
A10002240 als Beispiel

**Comment by finnbechinka** [comment]
Hmm also bei mir sind sowohl die Bilder als auch die Kategorie da: [log](https://prnt.sc/VeDpkKGSeaa_), [db](https://prnt.sc/wsnxVflVogew)

**Comment by VolkerSchroeder13** [comment]
'id': 'A10002240',
 'image_urls': ['https://www.aniforte.de/cdn/shop/products/indische-flohsamen-169289.jpg?v=1696980179&width=1200',
                'https://www.aniforte.de/cdn/shop/products/indische-flohsamen-1-kg-201389.jpg?v=1696919929&width=1200',
                'https://www.aniforte.de/cdn/shop/products/indische-flohsamen-489626.jpg?v=1696980179&width=1200',
                'https://www.aniforte.de/cdn/shop/products/indische-flohsamen-904114.jpg?v=1696919929&width=1200',
                'https://www.aniforte.de/cdn/shop/products/indische-flohsamen-690211.jpg?v=1696980179&width=1200',
                'https://www.aniforte.de/cdn/shop/products/indische-flohsamen-991803.jpg?v=1696980179&width=1200',
                'https://www.aniforte.de/cdn/shop/files/ReDesign_Indische_Flohsamen_Galeriebilder_1200x1200px_Produktbild_1kg.jpg?v=1699003591&width=1200'],
 'images': None,
 'parent': 'A10002240',
 'price': '9.99',
 'selector': 'Ergänzungsfuttermittel - Magen & Darm',
 'sid': 'A10002240',
 'size': '250',
 'time': None,
 'title': 'Indische Flohsamen',

**Comment by VolkerSchroeder13** [comment]
bei mir findet pims die Bilder, lädt sie aber anscheinend nicht runter.
seltsam

**Comment by VolkerSchroeder13** [comment]
Ich lösche jetzt Aniforte mal und versuche noch mal neu.
Aber wieso ist bei dir im Log das Produkt A10002240 und das Storage Verzeichnis A10000255?

**Comment by VolkerSchroeder13** [comment]
mmmh, gelöscht bekomme ich Aniforte nicht. Maurice hatte ja die Löschfunktion in Pims-Gui eingefügt, damit Produkte und Bilder (nicht die Kategorieabhängikeiten, die sollen bleiben) gelöscht werden können. Aber da dreht sich nur der Cursor im Kreis und ich bekomme "Keine Rückmeldung"

**Comment by finnbechinka** [comment]
Ja das ist glaube so weil 255 eine Variante von 2240 ist aber 255 zuerst dran kommt und der dann das Bild ja schon heruntergeladen hat und dass unter 255 abgespeichert ist. In der Datenbank ist das aber richtig verknüpft.

**Comment by finnbechinka** [comment]
> bei mir findet pims die Bilder, lädt sie aber anscheinend nicht runter.
> seltsam

Ist das bei allen Produkten oder nur bei manchen?

**Comment by VolkerSchroeder13** [comment]
ich hab gestern einen kompletten crawl angestossen. rund 15 sind durch, aber ohne auch nur ein neues Bild runterzuladen. das wäre sehr ungewöhnlich....

**Comment by finnbechinka** [comment]
Der Pfad, in dem die Bilder gespeichert werden muss in einen `.env` Datei, im Projektverzeichnis, stehen (so wie bei der GUI) und vielleicht ist die irgendwie weg?

Da müsste so etwas drin stehen: `PATH="D:\code\PIMS\PIMS\imgs"` halt nur mit dem gewünschten Pfad.

Mir fällt sonst auf Anhieb nichts anderes ein, warum das nicht funktionieren sollte.

**Comment by VolkerSchroeder13** [comment]
also die .env war definitiv weg. Ich hab vor ein paar Tagen PIMS neu gezogen und bei git fehlt die Datei. Daher war sie auch bei mir nicht drauf. 
Hab jetzt die .env aus dem PIMS-GUI Verzeichnis genommen. Die müsste ja passen.
Aber Bilder bekomme ich irgendwie immer noch nicht. Liest PIMS die bei jedem crawl neu ein?

Inhalt:
# PATH needs to be replaced with a folder path.
# ex.: EXPORT="C:/Users/User/Documents/exports"
STORAGE="V:/Scrape/Storage/"
EXPORT="V:/Scrape/Export/"

die / sind andersherum als bei dir.... aber so schauts im GUI Verzeichnis aus

**Comment by VolkerSchroeder13** [comment]
wie sieht die .env bei dir aus?

**Comment by finnbechinka** [comment]
Ja so wie ich [oben](https://github.com/PIMS-ORG/PIMS/issues/122#issuecomment-1819905296) geschrieben hatte. 
Also `PATH="x"` mit dem gewollten Ordner und da drin werden dann die `Storage` und `Export` Ordner automatisch erstellt.

Ist aus irgendeinem Grund bei PIMS und GUI unterschiedlich gemacht.

**Comment by VolkerSchroeder13** [comment]
jo, das wars :-) Danke :-)
